---
name: weepingangel
on:
  schedule:
    - cron: '0 10 * * *'
jobs:
  weepingangel:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GZBOT_GHPAT_WEEPINGANGEL }}
    steps:
      - name: Run weepingangel action
        uses: geekzonehq/reusable-workflows/.github/workflows/eisenhower.yml@main